### ISSUE TITLE
[PE-D][Tester D] Unable to 'view yesterday'

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-2/tp#101]
![image.png](https://raw.githubusercontent.com/verydaftpunk/ped/main/files/4ed604c4-1443-493f-9563-23f0cd304f10.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: verydaftpunk/ped#5

**Comment by Nafeij** [comment]
Not a bug
