### ISSUE TITLE
[PE-D][Tester C] [EVENT COMMAND] Time Clash not accounted for events.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W10-2/tp#108]
## Description:

When there are 2 time clashing events, the application accepts it anyway.
Considering that this application is something which helps you to manage your tasks, it does not help you in anyway, but kind of defeats the purpose.

## Screenshot:

![image.png](https://raw.githubusercontent.com/russelltankaimin/ped/main/files/b61782ef-6a19-4124-b112-b96e21c96e67.png)

## Expected:

Should indicate a clash (or even better, ask user to choose which task to keep)

## Actual

Accepts the task

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: russelltankaimin/ped#6

**Comment by Nafeij** [comment]
Note: add popup confirmation message

**Comment by Nafeij** [comment]
Feature Suggestion
