### ISSUE TITLE
[PE-D][Tester C] [Scope] A foreign student who does not know English is not able to enter items in their local language

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-2/tp#111]
## Description
Given that your scope is just University students, then a foreign student in a foreign university who does not know English would be unable to enter their tasks properly.

## Steps to reproduce:

Run `event t/お誕生日おめでとうfrom/20-03-2023 0000 to/20-03-2023 2359 l/Tokyo Hotel`

## Expected

Event to be added with the exact title present

## Actual
Invalid Command Format message feedbacked.

## Picture

![image.png](https://raw.githubusercontent.com/russelltankaimin/ped/main/files/e61b5f9c-e805-42bf-bff8-034b3385abc6.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: russelltankaimin/ped#7

**Comment by Nafeij** [comment]
Not a bug: title param is missing tailing whitespace
