### ISSUE TITLE
[PE-D][Tester C] [DELETE COMMAND] Unable to delete 2nd task even though I clearly have at least 2 tasks.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W10-2/tp#114]
## Description

I have at least 2 tasks. But I was not able to delete task 2 after `search` command is executed

## Steps to reproduce

Do the following events and tasks in this sequence: Task1 Event1 Task2 Event2

Do a `search` such that only Task 1 is shown.
I want to delete Task 2 or even Event 2 (I'm unsure because the markdown I am referring to [Not UG because it doesn't work]) 

Run `delete 2`

## Expected:
Either Event 1 or Task 2 deleted (Unsure), but I suspect it is Task 2, since it is task index.

## Actual:
Task Index provided is invalid.

## Picture

![image.png](https://raw.githubusercontent.com/russelltankaimin/ped/main/files/200ec6ec-4ffe-4c3a-b650-41579ca4ff9e.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: russelltankaimin/ped#10

**Comment by Nafeij** [comment]
Note: Update UG to specify that task_index referenced in commands refers to index of displayed task in filteredlist
