### ISSUE TITLE
Custom ICal Adapters for our backend

### ISSUE THREAD

**Issue by Enigmatrix** [AY2223S2-CS2103T-W10-2/tp#34]
Adapt JavaFX calendar backend to use our ical data directly using [custom adapters](https://github.com/dlsc-software-consulting-gmbh/CalendarFX/blob/master-11/CalendarFXGoogle/src/main/java/com/calendarfx/google/converter/EventToGoogleEntryConverter.java)

**Comment by Nafeij** [comment]
v1.5+: Future enhancement
