### ISSUE TITLE
As an NUS student/staff, I can add more information to tasks

### ISSUE THREAD

**Issue by Flash161203** [AY2223S2-CS2103T-W10-2/tp#54]
- As an NUS staff/student, I can set priorities for each of the tasks.

- As an NUS staff/student, I can mark my tasks as done or undone.
- As an NUS staff/student, I can add optional details to my tasks - descriptions, locations, comments

**Comment by vaidyanaath** [comment]
Completed in PR #72, #68, #70, #78
