### ISSUE TITLE
[PE-D][Tester D] Unable to add an overdue todo

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-2/tp#88]
![Screenshot 2023-03-31 at 2.30.53 PM.png](https://raw.githubusercontent.com/verydaftpunk/ped/main/files/2d56fba6-a2da-4424-89e4-ad76dc1dab28.png)
Screenshot 2023-03-31 at 2.30.53 PM

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: verydaftpunk/ped#1

**Comment by Nafeij** [comment]
Not a bug
