### ISSUE TITLE
[PE-D][Tester B] Adding events to past dates will not be allowed. The error message does not reflect that, only says that the format is wrong.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W10-2/tp#92]
It seems like we are unable to add events to previous passed dates. Not sure if that is intended, but could make that known through the error message!  
`event t/ CS3230 from/30-03-2023  1400 to/30-03-2023  1600 d/ Dynamic Programming l/ i3 Aud tag/Lecture`
![Screen Shot 2023-03-31 at 14.37.39 PM.png](https://raw.githubusercontent.com/ezeAng/ped/main/files/0c98a9d0-1379-4320-840d-37c3cf6a2310.png)

`event t/ CS3230 from/ 12-03-2023  1400 to/ 12-03-2023  1600 d/ Dynamic Programming l/ i3 Aud tag/Lecture`

`event t/CS3230 from/ 05-04-2023 1400 to/ 05-04-2023 1600 d/ Dynamic Programming l/ i3 Aud tag/ Lecture` works

**UPDATE**
Now it seems to work, I suspect it didnt work due to some other input previously or some existing event overlap. But the first 2 commands did not work in some scenarios.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ezeAng/ped#3

**Comment by Nafeij** [comment]
Note: Might want to remove validation for historical dates (allow users to add tasks in the past)

**Comment by Nafeij** [comment]
Not a bug: date-time in input contains double whitespace
